name: tests

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        env:
          ACCESS_KEY_ENV: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY_ENV: ${{ secrets.SECRET_KEY }}
        run: docker build --build-arg ACCESS_KEY_ARG=$ACCESS_KEY_ENV --build-arg SECRET_KEY_ARG=$SECRET_KEY_ENV --target test .